### PR TITLE
Mkdocs CI

### PR DESCRIPTION
**Pull request by oke-aditya**
Merge this PR before #200 . This sets up the CI so that subsequent doc builds can pass.

### CODE REVIEW

**Comment by oke-aditya** [comment]
The CI passes for it coz Github doesn't check new CI on PRs lol. I haven't removed old docs CI in this.

**Comment by oke-aditya** [comment]
Irrelevant failure. This has nothing to do with CI failure.

**Comment by lgvaz** [comment]
Merge with master, this error is fixed there

**Comment by ai-fast-track** [comment]
@oke-aditya, we will need your 2 new files: `mkdocs-build.yml`, and `mkdocs-deploy`.yml

**Comment by oke-aditya** [comment]
Yep will update it in an hour

**Comment by oke-aditya** [comment]
Should I remove the old docs yml files in this PR ?

**Comment by oke-aditya** [comment]
Helps #197.

**Comment by lgvaz** [comment]
Ow, it seems the actions can run before merging! cool!

**Comment by oke-aditya** [comment]
Yeah they run apparantely for the PR. But lets have this merged. Coz when I re-ran #200 These actions did not run.

**Comment by oke-aditya** [comment]
@ai-fast-track this is ready to merge now. I will re run #200 After this. If it works well then you can raise your PR. I do not want to merge #200 since it has nothing what our docs need. It is a test mkdocs.

**Comment by ai-fast-track** [comment]
Merged!

**Pull request merged**
