### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by oke-aditya**
- Do not merge as of now. I'm testing CI and docs preview.

### CODE REVIEW

**Comment by oke-aditya** [comment]
- Can someone just look into the toc_tree issue @lgvaz  @ai-fast-track . It seems to be a small fix. Do let me know and we are done with this refactor.

**Comment by ai-fast-track** [comment]
While updating the docs, please fix the following typo: **starring** instead of **staring** LOL!

This:
Note: If you find this work useful, please let other people know by **starring** it. Thank you!

instead of: 
Note: If you find this work useful, please let other people know by **staring** it. Thank you!

**Comment by oke-aditya** [comment]
Staring and starring are so different. Epic LOL

**Comment by lgvaz** [comment]
About the error, I don't see the directory `tutorials/mantisshrimp_models/`, you need to create that

**Comment by oke-aditya** [comment]
I forget to commit that. I had shifted the directories.

**Comment by oke-aditya** [comment]
Fixes #124.

**Comment by oke-aditya** [comment]
Now it looks good Probably we can merge this. And fix up if anything breaks.

**Comment by oke-aditya** [comment]
Oh it is `.nblink` files. I thought it was the tutorials folder outside. 😄 I will fix it.

**Comment by oke-aditya** [comment]
Fixed it. 😃

**Comment by oke-aditya** [comment]
Merge #126 First and then this. As this renames and shifts the files.

**Comment by lgvaz** [comment]
Alright, fingers crossed hahaha

**Comment by oke-aditya** [comment]
Suggestion for a very simple conflict fix. Delete this file. Merge the PR. Re-add this file with another PR.

**Pull request merged**
