### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by oke-aditya**
To add docker files. First, we need a CI-CD action to deploy it to docker hub.
The first step to #97 and #99.

@lgvaz you need to set up secrets as username and password for docker hub in your GitHub secrets action.

As described [here](https://medium.com/better-programming/github-actions-for-docker-eaf22bbcc879)

### CODE REVIEW

**Comment by lgvaz** [comment]
Will this work without a Dockerfile?

**Comment by oke-aditya** [comment]
Okay, I'm building locally. Once done will add PR for that too.

**Comment by lgvaz** [comment]
Just keep pushing to this PR =)

**Comment by oke-aditya** [comment]
Added minimal docker file. It should hopefully.

**Comment by oke-aditya** [comment]
Everything works locally now. @lgvaz setting up the Secrets with GitHub should and CI action should push this to docker hub as well. 

As we update the master new container will be created and pushed again to docker container hub.

**Comment by oke-aditya** [comment]
Yes, we can provide docker images with CUDA support as well as with No CUDA support (I guess this is useful for stuff like Raspberry Pi kinda devices). We need to tag them differently and need different Dockerfiles for both. Something which TensorFlow does [like this](https://hub.docker.com/r/tensorflow/tensorflow/tags). Currently, Dockerfile is built with torch GPU.

**Comment by oke-aditya** [comment]
It is done as in [here](https://docs.docker.com/config/containers/resource_constraints/). The current image is built for GPU. As it uses PyTorch GPU. User needs to follow these instructions to run NVIDIA drivers within their container.

**Comment by oke-aditya** [comment]
What best we can do is provide containers for both CPU and GPU separately. People need to setup their GPU using nvidia-docker and just run the container which will get created with this PR.

**Comment by lgvaz** [comment]
Alright then, let's merge this one and we keep adding more support as it needs

**Pull request merged**
