### PR TITLE
Added GPU Docker support

### PR DESCRIPTION
**Pull request by oke-aditya**
- Uses Docker best practices.
- I have checked it builds locally.
- Uses NVIDIA Docker GPU runtime. So torch accelerates with GPU.

Docker action is too changed so that it build with this.

### CODE REVIEW

**Comment by oke-aditya** [comment]
Will fix #97 . Helps in #99 . Helps in #98

**Comment by oke-aditya** [comment]
Yes. This single file does all the job of running torch and mantisshrimp on GPU, user just needs to have their GPU initialized properly.

**Comment by ai-fast-track** [comment]
I find it a bit confusing to have these 2 similar  issues (#97 and #106) running in parallel. Can we merge them?

**Comment by oke-aditya** [comment]
Clarification: -
This is CPU + GPU build. It works fine on CPU only devices as well.

Below are my screenshots when I tested it on CPU only device.
image

image

It will work fine on GPU device as well. It has torch-gpu installed.

**Comment by oke-aditya** [comment]
> 
> 
> Clarification: -
> This is CPU + GPU build. It works fine on CPU only devices as well.
> 
> Below are my screenshots when I tested it on CPU only device.
> image
> 
> image
> 
> It will work fine on GPU device as well. It has torch-gpu installed.

#97 is the only issue and #106 is the PR as solution to it. Which is this

**Comment by oke-aditya** [comment]
Fixed all the stuff. It is working absolutely fine. Able to import in both cases without absolute imports and with it too.

**Pull request merged**
