### PR TITLE
Fixes docs, tutorials, readme

### PR DESCRIPTION
**Pull request by oke-aditya**
- Updates tutorial
- Will fix Readme Broken Links too in one more commit.

### CODE REVIEW

**Comment by oke-aditya** [comment]
@lgvaz and @ai-fast-track please let me know if any chnages in readme docs or tutorials is required. Helps in #124

**Comment by lgvaz** [comment]
Docs build is failing with:
```
Notebook error:
Problems with linked notebook "tutorials/mantisshrimp_models/faster_rcnn_adv" path:
InputError: [Errno 2] No such file or directory: '../tutorials/mantisshrimp_models/2.faster_rcnn_advanced.ipynb'.
```

**Comment by oke-aditya** [comment]
Was a small typo in name `2.faster_rcnn_advanced .ipynb` was named which is changed to `2.faster_rcnn_advanced.ipynb`. Now it should be fine.

**Comment by lgvaz** [comment]
Works now! Thanks!

**Pull request merged**
