### PR TITLE
Update advanced Faster RCNN Tutorial

### PR DESCRIPTION
**Pull request by oke-aditya**
- Please have a review. I have ran the code on Kaggle and tranferred it here.

- Do let me know if some points are unclear for the engines.

### CODE REVIEW

**Comment by oke-aditya** [comment]
Closes #115 . Helps in #124 #39

**Comment by oke-aditya** [comment]
Helps #111

**Comment by lgvaz** [comment]
@ai-fast-track, can we have your thoughts?

I still think there is too much overlap between the quickstart tutorial and this one, I'm thinking users will first always read the quickstart and then come to this.

Ideally we want no overlap between the two, as I user am inclined to just start scrolling the to tutorial once I realise there is repetition.

**Comment by oke-aditya** [comment]
<p>Changed.</p>

---

 <a href='https://app.reviewnb.com/lgvaz/mantisshrimp/pull/126/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by oke-aditya** [comment]
<p>Fixed.</p>

---

 <a href='https://app.reviewnb.com/lgvaz/mantisshrimp/pull/126/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by oke-aditya** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/lgvaz/mantisshrimp/pull/126/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by oke-aditya** [comment]
<p>Added</p>

---

 <a href='https://app.reviewnb.com/lgvaz/mantisshrimp/pull/126/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by oke-aditya** [comment]
<p>Yes, we can have trained model. We desperately need a good model to show some good results.</p>

---

 <a href='https://app.reviewnb.com/lgvaz/mantisshrimp/pull/126/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by oke-aditya** [comment]
<p>Cleans comments</p>

---

 <a href='https://app.reviewnb.com/lgvaz/mantisshrimp/pull/126/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by oke-aditya** [comment]
<ul><li>I guess it is bettor to have 2 tutorials. As people like a quick overview and giving a depth guide would reinforce the ideas.</li><li>Also it becomes more easier to explain these advanced concepts. Otherwise it will be hard to tell them how backbones work.</li></ul>

**Pull request merged**
